"""alarm mess 

Revision ID: 094b8df49560
Revises: cadeea25a5dc
Create Date: 2026-01-10 13:04:07.881826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094b8df49560'
down_revision: Union[str, Sequence[str], None] = 'cadeea25a5dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.Integer, nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarm_messages_device_id'), 'alarm_messages', ['device_id'], unique=False)
    op.create_index(op.f('ix_alarm_messages_user_id'), 'alarm_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alarm_messages_user_id'), table_name='alarm_messages')
    op.drop_index(op.f('ix_alarm_messages_device_id'), table_name='alarm_messages')
    op.drop_table('alarm_messages')
    # ### end Alembic commands ###
