"""Schedule

Revision ID: 128f05640c36
Revises: 6c78eb3ac62f
Create Date: 2026-01-08 15:04:59.859689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '128f05640c36'
down_revision: Union[str, Sequence[str], None] = '6c78eb3ac62f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_recording_mode_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('mode', sa.Enum('CMR', 'MOTION', 'ALARM', 'EDR', 'ALARMANDMOTION', 'AllEvent', name='recordingmode'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_channel_day_time', 'channel_recording_mode_timeline', ['channel_id', 'day_of_week', 'start_time'], unique=False)
    op.create_index(op.f('ix_channel_recording_mode_timeline_channel_id'), 'channel_recording_mode_timeline', ['channel_id'], unique=False)
    op.create_table('channel_recordings_mode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('default_mode', sa.Enum('CMR', 'MOTION', 'ALARM', 'EDR', 'ALARMANDMOTION', 'AllEvent', name='recordingmode'), nullable=False),
    sa.Column('schedule_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_recordings_mode_channel_id'), 'channel_recordings_mode', ['channel_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_recordings_mode_channel_id'), table_name='channel_recordings_mode')
    op.drop_table('channel_recordings_mode')
    op.drop_index(op.f('ix_channel_recording_mode_timeline_channel_id'), table_name='channel_recording_mode_timeline')
    op.drop_index('ix_channel_day_time', table_name='channel_recording_mode_timeline')
    op.drop_table('channel_recording_mode_timeline')
    # ### end Alembic commands ###
