"""update device_storage + intergration_user 

Revision ID: 1fe1099481ad
Revises: af289607a163
Create Date: 2025-12-30 08:31:06.619258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe1099481ad'
down_revision: Union[str, Sequence[str], None] = 'af289607a163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_integration_users', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_column('device_integration_users', 'is_active')
    op.add_column('device_storage', sa.Column('hdd_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_storage', 'hdd_type')
    op.add_column('device_integration_users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('device_integration_users', 'user_id')
    # ### end Alembic commands ###
