"""Ok last , I hope 

Revision ID: 48076378d8ef
Revises: dc03693cd7f5
Create Date: 2025-12-30 15:03:24.745461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48076378d8ef'
down_revision: Union[str, Sequence[str], None] = 'dc03693cd7f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('user_channel_permissions', sa.Column('permission', sa.String(length=30), nullable=True))
    op.add_column('user_channel_permissions', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_user_channel_permission_device_user_channel'), table_name='user_channel_permissions')
    op.create_index('ix_user_channel_permission_unique', 'user_channel_permissions', ['device_user_id', 'channel_id', 'scope', 'permission'], unique=True)
    op.drop_column('user_channel_permissions', 'backup')
    op.drop_column('user_channel_permissions', 'playback')
    op.drop_column('user_channel_permissions', 'record')
    op.drop_column('user_channel_permissions', 'ptz_control')
    op.drop_column('user_channel_permissions', 'preview')
    op.add_column('user_global_permissions', sa.Column('control_local_out', sa.Boolean(), nullable=True))
    op.add_column('user_global_permissions', sa.Column('transparent_channel', sa.Boolean(), nullable=True))
    op.drop_column('user_global_permissions', 'video_out_put_control')
    op.drop_column('user_global_permissions', 'serial_port')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_global_permissions', sa.Column('serial_port', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user_global_permissions', sa.Column('video_out_put_control', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user_global_permissions', 'transparent_channel')
    op.drop_column('user_global_permissions', 'control_local_out')
    op.add_column('user_channel_permissions', sa.Column('preview', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user_channel_permissions', sa.Column('ptz_control', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user_channel_permissions', sa.Column('record', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user_channel_permissions', sa.Column('playback', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user_channel_permissions', sa.Column('backup', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index('ix_user_channel_permission_unique', table_name='user_channel_permissions')
    op.create_index(op.f('ix_user_channel_permission_device_user_channel'), 'user_channel_permissions', ['device_user_id', 'channel_id'], unique=False)
    op.drop_column('user_channel_permissions', 'enabled')
    op.drop_column('user_channel_permissions', 'permission')
    op.alter_column('sync_settings', 'owner_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('sync_logs', 'owner_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('monitor_settings', 'owner_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###
