"""OK 

Revision ID: 485136cdac95
Revises: 6ef9f8b6042d
Create Date: 2026-01-02 08:38:22.294894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485136cdac95'
down_revision: Union[str, Sequence[str], None] = '6ef9f8b6042d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_channel_permissions_device_user_id_fkey'), 'user_channel_permissions', type_='foreignkey')
    op.drop_constraint(op.f('user_global_permissions_device_user_id_fkey'), 'user_global_permissions', type_='foreignkey')
    op.drop_constraint(op.f('uq_user_id'), 'device_users', type_='unique')
    op.alter_column('device_users', 'device_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    
    op.create_unique_constraint('uq_device_user', 'device_users', ['device_id', 'user_id'])
    op.alter_column('user_channel_permissions', 'device_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_channel_permissions', 'channel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_channel_permissions', 'scope',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('user_channel_permissions', 'permission',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
   
    op.create_foreign_key(None, 'user_channel_permissions', 'device_users', ['device_user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_global_permission_user_scope'), table_name='user_global_permissions')
    op.create_index('ix_user_global_permission_unique', 'user_global_permissions', ['device_user_id', 'scope'], unique=True)
    
    op.create_foreign_key(None, 'user_global_permissions', 'device_users', ['device_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_global_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('user_global_permissions_device_user_id_fkey'), 'user_global_permissions', 'device_users', ['device_user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index('ix_user_global_permission_unique', table_name='user_global_permissions')
    op.create_index(op.f('ix_user_global_permission_user_scope'), 'user_global_permissions', ['device_user_id', 'scope'], unique=True)
    op.drop_constraint(None, 'user_channel_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('user_channel_permissions_device_user_id_fkey'), 'user_channel_permissions', 'device_users', ['device_user_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('user_channel_permissions', 'permission',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user_channel_permissions', 'scope',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('user_channel_permissions', 'channel_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_channel_permissions', 'device_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_device_user', 'device_users', type_='unique')
    op.create_unique_constraint(op.f('uq_user_id'), 'device_users', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('device_users', 'device_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
