"""add channel and event to alarm_messages

Revision ID: 4c71e6bb2f85
Revises: 8f026358d516
Create Date: 2026-01-17 16:06:05.134385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c71e6bb2f85'
down_revision: Union[str, Sequence[str], None] = '8f026358d516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm_messages', sa.Column('channel_id_in_device', sa.String(length=32), nullable=True))
    op.add_column('alarm_messages', sa.Column('channel_name', sa.String(length=255), nullable=True))
    op.add_column('alarm_messages', sa.Column('event', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_alarm_messages_channel_id_in_device'), 'alarm_messages', ['channel_id_in_device'], unique=False)
    op.create_index(op.f('ix_alarm_messages_event'), 'alarm_messages', ['event'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alarm_messages_event'), table_name='alarm_messages')
    op.drop_index(op.f('ix_alarm_messages_channel_id_in_device'), table_name='alarm_messages')
    op.drop_column('alarm_messages', 'event')
    op.drop_column('alarm_messages', 'channel_name')
    op.drop_column('alarm_messages', 'channel_id_in_device')
    # ### end Alembic commands ###
