"""them cai monitor setting

Revision ID: 5363f691e6c2
Revises: dfac9d1ecdc0
Create Date: 2025-12-24 14:40:08.799959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5363f691e6c2'
down_revision: Union[str, Sequence[str], None] = 'dfac9d1ecdc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_day', sa.Integer(), nullable=True),
    sa.Column('end_day', sa.Integer(), nullable=True),
    sa.Column('order', sa.Boolean(), nullable=True),
    sa.Column('owner_superadmin_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitor_settings')
    # ### end Alembic commands ###
