"""update channel model + extension vì zero channel là toàn system not channel 

Revision ID: 645ed8c382ba
Revises: 8a4a4635ddc5
Create Date: 2025-12-29 11:30:12.775148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '645ed8c382ba'
down_revision: Union[str, Sequence[str], None] = '8a4a4635ddc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel_extensions', 'zero_stream_enabled')
    op.add_column('channels', sa.Column('connected_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'connected_type')
    op.add_column('channel_extensions', sa.Column('zero_stream_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
