"""Update bit rate channel  

Revision ID: 6c78eb3ac62f
Revises: 485136cdac95
Create Date: 2026-01-06 10:47:50.430306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c78eb3ac62f'
down_revision: Union[str, Sequence[str], None] = '485136cdac95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_stream_configs', sa.Column('vbr_upper_cap', sa.Integer(), nullable=True))
    op.add_column('channel_stream_configs', sa.Column('h265_plus', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel_stream_configs', 'h256_plus')
    op.drop_column('channel_stream_configs', 'vbr_upper_cap')
    # ### end Alembic commands ###
