"""Fuck all this, permission and shit 

Revision ID: 6ef9f8b6042d
Revises: bc463c4b4639
Create Date: 2025-12-31 10:41:15.423176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef9f8b6042d'
down_revision: Union[str, Sequence[str], None] = 'bc463c4b4639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_id', 'device_users', ['user_id'])
    op.drop_constraint(op.f('user_channel_permissions_device_user_id_fkey'), 'user_channel_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'user_channel_permissions', 'device_users', ['device_user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_global_permissions_device_user_id_fkey'), 'user_global_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'user_global_permissions', 'device_users', ['device_user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_global_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('user_global_permissions_device_user_id_fkey'), 'user_global_permissions', 'device_users', ['device_user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_channel_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('user_channel_permissions_device_user_id_fkey'), 'user_channel_permissions', 'device_users', ['device_user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_user_id', 'device_users', type_='unique')
    # ### end Alembic commands ###
