"""1 ty table

Revision ID: 8a4a4635ddc5
Revises: 8d358e4d5b55
Create Date: 2025-12-27 16:40:40.467980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a4a4635ddc5'
down_revision: Union[str, Sequence[str], None] = '8d358e4d5b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_integration_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('hdd_id', sa.Integer(), nullable=True),
    sa.Column('hdd_name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('free_space', sa.Integer(), nullable=True),
    sa.Column('property', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_system_info',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('device_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_extensions',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('zero_stream_enabled', sa.Boolean(), nullable=True),
    sa.Column('motion_detect_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_table('channel_stream_configs',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('resolution_width', sa.Integer(), nullable=True),
    sa.Column('resolution_height', sa.Integer(), nullable=True),
    sa.Column('video_codec', sa.String(length=20), nullable=True),
    sa.Column('max_frame_rate', sa.Integer(), nullable=True),
    sa.Column('vbr_average_cap', sa.Integer(), nullable=True),
    sa.Column('fixed_quality', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_table('user_channel_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_user_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=10), nullable=True),
    sa.Column('preview', sa.Boolean(), nullable=True),
    sa.Column('playback', sa.Boolean(), nullable=True),
    sa.Column('record', sa.Boolean(), nullable=True),
    sa.Column('backup', sa.Boolean(), nullable=True),
    sa.Column('ptz_control', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_user_id'], ['device_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_channel_permission_device_user_channel', 'user_channel_permissions', ['device_user_id', 'channel_id'], unique=False)
    op.create_table('user_global_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_user_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=10), nullable=True),
    sa.Column('backup', sa.Boolean(), nullable=True),
    sa.Column('record', sa.Boolean(), nullable=True),
    sa.Column('playback', sa.Boolean(), nullable=True),
    sa.Column('preview', sa.Boolean(), nullable=True),
    sa.Column('log_or_state_check', sa.Boolean(), nullable=True),
    sa.Column('parameter_config', sa.Boolean(), nullable=True),
    sa.Column('restart_or_shutdown', sa.Boolean(), nullable=True),
    sa.Column('upgrade', sa.Boolean(), nullable=True),
    sa.Column('voice_talk', sa.Boolean(), nullable=True),
    sa.Column('alarm_out_or_upload', sa.Boolean(), nullable=True),
    sa.Column('serial_port', sa.Boolean(), nullable=True),
    sa.Column('video_out_put_control', sa.Boolean(), nullable=True),
    sa.Column('manage_channel', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['device_user_id'], ['device_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_global_permissions')
    op.drop_index('ix_user_channel_permission_device_user_channel', table_name='user_channel_permissions')
    op.drop_table('user_channel_permissions')
    op.drop_table('channel_stream_configs')
    op.drop_table('channel_extensions')
    op.drop_table('device_users')
    op.drop_table('device_system_info')
    op.drop_table('device_storage')
    op.drop_table('device_integration_users')
    # ### end Alembic commands ###
