"""thêm column channel 

Revision ID: 8d358e4d5b55
Revises: 5363f691e6c2
Create Date: 2025-12-25 10:48:51.917323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d358e4d5b55'
down_revision: Union[str, Sequence[str], None] = '5363f691e6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('channels', sa.Column('last_channel_sync_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'last_channel_sync_at')
    op.drop_column('channels', 'is_active')
    # ### end Alembic commands ###
