"""empty message

Revision ID: 8f026358d516
Revises: 094b8df49560
Create Date: 2026-01-13 14:58:09.626205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f026358d516'
down_revision: Union[str, Sequence[str], None] = '094b8df49560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_alarm_user_created_at', 'alarm_messages', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_alarm_user_created_at', table_name='alarm_messages')
    # ### end Alembic commands ###
