"""How tf i never notice 

Revision ID: 9c08c94ca10e
Revises: 4c71e6bb2f85
Create Date: 2026-01-19 16:06:27.082581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c08c94ca10e'
down_revision: Union[str, Sequence[str], None] = '4c71e6bb2f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_global_permissions', sa.Column('ptz_control', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_global_permissions', 'ptz_control')
    # ### end Alembic commands ###
