"""Chinh channel thêm connected type và bo zero 

Revision ID: af289607a163
Revises: 8a4a4635ddc5
Create Date: 2025-12-29 13:20:47.896219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af289607a163'
down_revision: Union[str, Sequence[str], None] = '8a4a4635ddc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel_extensions', 'zero_stream_enabled')
    op.add_column('channels', sa.Column('connected_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'connected_type')
    op.add_column('channel_extensions', sa.Column('zero_stream_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
