"""should have read the model first 

Revision ID: bc463c4b4639
Revises: e3e1e1d2bb93
Create Date: 2025-12-31 08:51:52.392767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc463c4b4639'
down_revision: Union[str, Sequence[str], None] = 'e3e1e1d2bb93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('user_global_permissions', 'device_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_global_permissions', 'scope',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.create_index('ix_user_global_permission_user_scope', 'user_global_permissions', ['device_user_id', 'scope'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_global_permission_user_scope', table_name='user_global_permissions')
    op.alter_column('user_global_permissions', 'scope',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('user_global_permissions', 'device_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sync_settings', 'owner_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('sync_logs', 'owner_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('monitor_settings', 'owner_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###
