"""i forgot 

Revision ID: cadeea25a5dc
Revises: 128f05640c36
Create Date: 2026-01-08 15:48:58.000912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cadeea25a5dc'
down_revision: Union[str, Sequence[str], None] = '128f05640c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_recording_mode_timeline', sa.Column('day_end_of_week', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel_recording_mode_timeline', 'day_end_of_week')
    # ### end Alembic commands ###
