"""Fuckkkk 

Revision ID: dc03693cd7f5
Revises: 8c25544e0e1a
Create Date: 2025-12-30 14:06:38.649009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc03693cd7f5'
down_revision: Union[str, Sequence[str], None] = '8c25544e0e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('monitor_settings', sa.Column('owner_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'monitor_settings', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('sync_logs', sa.Column('owner_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'sync_logs', 'users', ['owner_id'], ['id'])
    op.add_column('sync_settings', sa.Column('owner_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'sync_settings', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sync_settings', type_='foreignkey')
    op.drop_column('sync_settings', 'owner_id')
    op.drop_constraint(None, 'sync_logs', type_='foreignkey')
    op.drop_column('sync_logs', 'owner_id')
    op.drop_constraint(None, 'monitor_settings', type_='foreignkey')
    op.drop_column('monitor_settings', 'owner_id')
    op.create_table('user_global_permissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scope', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('backup', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('record', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('playback', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('preview', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('log_or_state_check', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('parameter_config', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('restart_or_shutdown', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('upgrade', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('voice_talk', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('alarm_out_or_upload', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('serial_port', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('video_out_put_control', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('manage_channel', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_user_id'], ['device_users.id'], name=op.f('user_global_permissions_device_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_global_permissions_pkey')),
    sa.UniqueConstraint('device_user_id', name=op.f('user_global_permissions_device_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('user_channel_permissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scope', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('preview', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('playback', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('record', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('backup', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ptz_control', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('user_channel_permissions_channel_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_user_id'], ['device_users.id'], name=op.f('user_channel_permissions_device_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_channel_permissions_pkey'))
    )
    op.create_index(op.f('ix_user_channel_permission_device_user_channel'), 'user_channel_permissions', ['device_user_id', 'channel_id'], unique=False)
    # ### end Alembic commands ###
