"""table for channel

Revision ID: dfac9d1ecdc0
Revises: f78d26df5cf8
Create Date: 2025-12-22 09:19:58.211674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfac9d1ecdc0'
down_revision: Union[str, Sequence[str], None] = 'f78d26df5cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('channel_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('oldest_record_date', sa.Date(), nullable=True),
    sa.Column('latest_record_date', sa.Date(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_latest_record_date'), 'channels', ['latest_record_date'], unique=False)
    op.create_index(op.f('ix_channels_oldest_record_date'), 'channels', ['oldest_record_date'], unique=False)
    op.create_index('ix_device_channel_unique', 'channels', ['device_id', 'channel_no'], unique=True)
    op.create_table('channel_record_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('has_record', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_channel_record_day_unique', 'channel_record_days', ['channel_id', 'record_date'], unique=True)
    op.create_index(op.f('ix_channel_record_days_channel_id'), 'channel_record_days', ['channel_id'], unique=False)
    op.create_table('channel_record_time_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_day_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['record_day_id'], ['channel_record_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_record_time_ranges_record_day_id'), 'channel_record_time_ranges', ['record_day_id'], unique=False)
    op.create_index('ix_record_day_time_range', 'channel_record_time_ranges', ['record_day_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_record_day_time_range', table_name='channel_record_time_ranges')
    op.drop_index(op.f('ix_channel_record_time_ranges_record_day_id'), table_name='channel_record_time_ranges')
    op.drop_table('channel_record_time_ranges')
    op.drop_index(op.f('ix_channel_record_days_channel_id'), table_name='channel_record_days')
    op.drop_index('ix_channel_record_day_unique', table_name='channel_record_days')
    op.drop_table('channel_record_days')
    op.drop_index('ix_device_channel_unique', table_name='channels')
    op.drop_index(op.f('ix_channels_oldest_record_date'), table_name='channels')
    op.drop_index(op.f('ix_channels_latest_record_date'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
