"""fcukkkkkkkkkkk 

Revision ID: e3e1e1d2bb93
Revises: 48076378d8ef
Create Date: 2025-12-30 16:47:03.651795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3e1e1d2bb93'
down_revision: Union[str, Sequence[str], None] = '48076378d8ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_constraint(op.f('user_global_permissions_device_user_id_key'), 'user_global_permissions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_global_permissions_device_user_id_key'), 'user_global_permissions', ['device_user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('sync_settings', 'owner_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('sync_logs', 'owner_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('monitor_settings', 'owner_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###
